[package]
name = "vui-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
vui-core = { path = "../../core" }
vui-widgets = { path = "../../widgets" }
sdl2 = { version = "0.36", features = ["ttf", "gfx"] }